package commons;

public enum BrowserList {
	FIREFOX,FIREFOX_SETUP, FIREFOX_SETUP_VERSION, H_FIREFOX, H_FIREFOX_SETUP, 
	CHROME,	 CHROME_SETUP, 	CHROME_SETUP_VERSION, H_CHROME,  H_CHROME_SETUP, 
	EDGE, 	   EDGE_SETUP, 	  EDGE_SETUP_VERSION, H_EDGE, 	 H_EDGE_SETUP, 
	IE,			 IE_SETUP,		IE_SETUP_VERSION, H_IE,		 H_IE_SETUP, 
	OPERA, 	  OPERA_SETUP, 	 OPERA_SETUP_VERSION, H_OPERA,	 H_OPERA_SETUP, 
	COCCOC,  COCCOC_SETUP, 	COCCOC_SETUP_VERSION, H_COCCOC,	 H_COCCOC_SETUP, 
	BRAVE,    BRAVE_SETUP, 	 BRAVE_SETUP_VERSION, H_BRAVE, 	 H_BRAVE_SETUP, 
	PHANTOM;
}
