package commons;

public enum BrowserList {
	FIREFOX, FIREFOX_SETUP, FIREFOX_SETUP_VERSION, H_FIREFOX, H_FIREFOX_SETUP, CHROME, CHROME_SETUP, CHROME_SETUP_VERSION, H_CHROME, H_CHROME_SETUP, EDGE, IE, OPERA, COCCOC, BRAVE, PHANTOM;
}
